// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/heartbeat.proto

#include "flwr/proto/heartbeat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace flwr {
namespace proto {
constexpr SendNodeHeartbeatRequest::SendNodeHeartbeatRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : node_(nullptr)
  , heartbeat_interval_(0){}
struct SendNodeHeartbeatRequestDefaultTypeInternal {
  constexpr SendNodeHeartbeatRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SendNodeHeartbeatRequestDefaultTypeInternal() {}
  union {
    SendNodeHeartbeatRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SendNodeHeartbeatRequestDefaultTypeInternal _SendNodeHeartbeatRequest_default_instance_;
constexpr SendNodeHeartbeatResponse::SendNodeHeartbeatResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : success_(false){}
struct SendNodeHeartbeatResponseDefaultTypeInternal {
  constexpr SendNodeHeartbeatResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SendNodeHeartbeatResponseDefaultTypeInternal() {}
  union {
    SendNodeHeartbeatResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SendNodeHeartbeatResponseDefaultTypeInternal _SendNodeHeartbeatResponse_default_instance_;
constexpr SendAppHeartbeatRequest::SendAppHeartbeatRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : token_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SendAppHeartbeatRequestDefaultTypeInternal {
  constexpr SendAppHeartbeatRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SendAppHeartbeatRequestDefaultTypeInternal() {}
  union {
    SendAppHeartbeatRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SendAppHeartbeatRequestDefaultTypeInternal _SendAppHeartbeatRequest_default_instance_;
constexpr SendAppHeartbeatResponse::SendAppHeartbeatResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : success_(false){}
struct SendAppHeartbeatResponseDefaultTypeInternal {
  constexpr SendAppHeartbeatResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SendAppHeartbeatResponseDefaultTypeInternal() {}
  union {
    SendAppHeartbeatResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SendAppHeartbeatResponseDefaultTypeInternal _SendAppHeartbeatResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_flwr_2fproto_2fheartbeat_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_flwr_2fproto_2fheartbeat_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_flwr_2fproto_2fheartbeat_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_flwr_2fproto_2fheartbeat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendNodeHeartbeatRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendNodeHeartbeatRequest, node_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendNodeHeartbeatRequest, heartbeat_interval_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendNodeHeartbeatResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendNodeHeartbeatResponse, success_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendAppHeartbeatRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendAppHeartbeatRequest, token_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendAppHeartbeatResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::SendAppHeartbeatResponse, success_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::flwr::proto::SendNodeHeartbeatRequest)},
  { 8, -1, -1, sizeof(::flwr::proto::SendNodeHeartbeatResponse)},
  { 15, -1, -1, sizeof(::flwr::proto::SendAppHeartbeatRequest)},
  { 22, -1, -1, sizeof(::flwr::proto::SendAppHeartbeatResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::flwr::proto::_SendNodeHeartbeatRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::flwr::proto::_SendNodeHeartbeatResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::flwr::proto::_SendAppHeartbeatRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::flwr::proto::_SendAppHeartbeatResponse_default_instance_),
};

const char descriptor_table_protodef_flwr_2fproto_2fheartbeat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032flwr/proto/heartbeat.proto\022\nflwr.proto"
  "\032\025flwr/proto/node.proto\"V\n\030SendNodeHeart"
  "beatRequest\022\036\n\004node\030\001 \001(\0132\020.flwr.proto.N"
  "ode\022\032\n\022heartbeat_interval\030\002 \001(\001\",\n\031SendN"
  "odeHeartbeatResponse\022\017\n\007success\030\001 \001(\010\"(\n"
  "\027SendAppHeartbeatRequest\022\r\n\005token\030\001 \001(\t\""
  "+\n\030SendAppHeartbeatResponse\022\017\n\007success\030\001"
  " \001(\010b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_flwr_2fproto_2fheartbeat_2eproto_deps[1] = {
  &::descriptor_table_flwr_2fproto_2fnode_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_flwr_2fproto_2fheartbeat_2eproto = {
  false, false, 292, descriptor_table_protodef_flwr_2fproto_2fheartbeat_2eproto, "flwr/proto/heartbeat.proto", 
  &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once, descriptor_table_flwr_2fproto_2fheartbeat_2eproto_deps, 1, 4,
  schemas, file_default_instances, TableStruct_flwr_2fproto_2fheartbeat_2eproto::offsets,
  file_level_metadata_flwr_2fproto_2fheartbeat_2eproto, file_level_enum_descriptors_flwr_2fproto_2fheartbeat_2eproto, file_level_service_descriptors_flwr_2fproto_2fheartbeat_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_flwr_2fproto_2fheartbeat_2eproto_getter() {
  return &descriptor_table_flwr_2fproto_2fheartbeat_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_flwr_2fproto_2fheartbeat_2eproto(&descriptor_table_flwr_2fproto_2fheartbeat_2eproto);
namespace flwr {
namespace proto {

// ===================================================================

class SendNodeHeartbeatRequest::_Internal {
 public:
  static const ::flwr::proto::Node& node(const SendNodeHeartbeatRequest* msg);
};

const ::flwr::proto::Node&
SendNodeHeartbeatRequest::_Internal::node(const SendNodeHeartbeatRequest* msg) {
  return *msg->node_;
}
void SendNodeHeartbeatRequest::clear_node() {
  if (GetArenaForAllocation() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
}
SendNodeHeartbeatRequest::SendNodeHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:flwr.proto.SendNodeHeartbeatRequest)
}
SendNodeHeartbeatRequest::SendNodeHeartbeatRequest(const SendNodeHeartbeatRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::flwr::proto::Node(*from.node_);
  } else {
    node_ = nullptr;
  }
  heartbeat_interval_ = from.heartbeat_interval_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.SendNodeHeartbeatRequest)
}

void SendNodeHeartbeatRequest::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&node_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&heartbeat_interval_) -
    reinterpret_cast<char*>(&node_)) + sizeof(heartbeat_interval_));
}

SendNodeHeartbeatRequest::~SendNodeHeartbeatRequest() {
  // @@protoc_insertion_point(destructor:flwr.proto.SendNodeHeartbeatRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SendNodeHeartbeatRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void SendNodeHeartbeatRequest::ArenaDtor(void* object) {
  SendNodeHeartbeatRequest* _this = reinterpret_cast< SendNodeHeartbeatRequest* >(object);
  (void)_this;
}
void SendNodeHeartbeatRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendNodeHeartbeatRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SendNodeHeartbeatRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.SendNodeHeartbeatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && node_ != nullptr) {
    delete node_;
  }
  node_ = nullptr;
  heartbeat_interval_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendNodeHeartbeatRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .flwr.proto.Node node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double heartbeat_interval = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          heartbeat_interval_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendNodeHeartbeatRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.SendNodeHeartbeatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  // double heartbeat_interval = 2;
  if (!(this->_internal_heartbeat_interval() <= 0 && this->_internal_heartbeat_interval() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_heartbeat_interval(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.SendNodeHeartbeatRequest)
  return target;
}

size_t SendNodeHeartbeatRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.SendNodeHeartbeatRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }

  // double heartbeat_interval = 2;
  if (!(this->_internal_heartbeat_interval() <= 0 && this->_internal_heartbeat_interval() >= 0)) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendNodeHeartbeatRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SendNodeHeartbeatRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendNodeHeartbeatRequest::GetClassData() const { return &_class_data_; }

void SendNodeHeartbeatRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SendNodeHeartbeatRequest *>(to)->MergeFrom(
      static_cast<const SendNodeHeartbeatRequest &>(from));
}


void SendNodeHeartbeatRequest::MergeFrom(const SendNodeHeartbeatRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.SendNodeHeartbeatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::flwr::proto::Node::MergeFrom(from._internal_node());
  }
  if (!(from._internal_heartbeat_interval() <= 0 && from._internal_heartbeat_interval() >= 0)) {
    _internal_set_heartbeat_interval(from._internal_heartbeat_interval());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendNodeHeartbeatRequest::CopyFrom(const SendNodeHeartbeatRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.SendNodeHeartbeatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendNodeHeartbeatRequest::IsInitialized() const {
  return true;
}

void SendNodeHeartbeatRequest::InternalSwap(SendNodeHeartbeatRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SendNodeHeartbeatRequest, heartbeat_interval_)
      + sizeof(SendNodeHeartbeatRequest::heartbeat_interval_)
      - PROTOBUF_FIELD_OFFSET(SendNodeHeartbeatRequest, node_)>(
          reinterpret_cast<char*>(&node_),
          reinterpret_cast<char*>(&other->node_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SendNodeHeartbeatRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_getter, &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once,
      file_level_metadata_flwr_2fproto_2fheartbeat_2eproto[0]);
}

// ===================================================================

class SendNodeHeartbeatResponse::_Internal {
 public:
};

SendNodeHeartbeatResponse::SendNodeHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:flwr.proto.SendNodeHeartbeatResponse)
}
SendNodeHeartbeatResponse::SendNodeHeartbeatResponse(const SendNodeHeartbeatResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.SendNodeHeartbeatResponse)
}

void SendNodeHeartbeatResponse::SharedCtor() {
success_ = false;
}

SendNodeHeartbeatResponse::~SendNodeHeartbeatResponse() {
  // @@protoc_insertion_point(destructor:flwr.proto.SendNodeHeartbeatResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SendNodeHeartbeatResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SendNodeHeartbeatResponse::ArenaDtor(void* object) {
  SendNodeHeartbeatResponse* _this = reinterpret_cast< SendNodeHeartbeatResponse* >(object);
  (void)_this;
}
void SendNodeHeartbeatResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendNodeHeartbeatResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SendNodeHeartbeatResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.SendNodeHeartbeatResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendNodeHeartbeatResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendNodeHeartbeatResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.SendNodeHeartbeatResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.SendNodeHeartbeatResponse)
  return target;
}

size_t SendNodeHeartbeatResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.SendNodeHeartbeatResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendNodeHeartbeatResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SendNodeHeartbeatResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendNodeHeartbeatResponse::GetClassData() const { return &_class_data_; }

void SendNodeHeartbeatResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SendNodeHeartbeatResponse *>(to)->MergeFrom(
      static_cast<const SendNodeHeartbeatResponse &>(from));
}


void SendNodeHeartbeatResponse::MergeFrom(const SendNodeHeartbeatResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.SendNodeHeartbeatResponse)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _internal_set_success(from._internal_success());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendNodeHeartbeatResponse::CopyFrom(const SendNodeHeartbeatResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.SendNodeHeartbeatResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendNodeHeartbeatResponse::IsInitialized() const {
  return true;
}

void SendNodeHeartbeatResponse::InternalSwap(SendNodeHeartbeatResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(success_, other->success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendNodeHeartbeatResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_getter, &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once,
      file_level_metadata_flwr_2fproto_2fheartbeat_2eproto[1]);
}

// ===================================================================

class SendAppHeartbeatRequest::_Internal {
 public:
};

SendAppHeartbeatRequest::SendAppHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:flwr.proto.SendAppHeartbeatRequest)
}
SendAppHeartbeatRequest::SendAppHeartbeatRequest(const SendAppHeartbeatRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_token().empty()) {
    token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_token(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:flwr.proto.SendAppHeartbeatRequest)
}

void SendAppHeartbeatRequest::SharedCtor() {
token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SendAppHeartbeatRequest::~SendAppHeartbeatRequest() {
  // @@protoc_insertion_point(destructor:flwr.proto.SendAppHeartbeatRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SendAppHeartbeatRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  token_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SendAppHeartbeatRequest::ArenaDtor(void* object) {
  SendAppHeartbeatRequest* _this = reinterpret_cast< SendAppHeartbeatRequest* >(object);
  (void)_this;
}
void SendAppHeartbeatRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendAppHeartbeatRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SendAppHeartbeatRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.SendAppHeartbeatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  token_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendAppHeartbeatRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_token();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "flwr.proto.SendAppHeartbeatRequest.token"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendAppHeartbeatRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.SendAppHeartbeatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string token = 1;
  if (!this->_internal_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "flwr.proto.SendAppHeartbeatRequest.token");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_token(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.SendAppHeartbeatRequest)
  return target;
}

size_t SendAppHeartbeatRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.SendAppHeartbeatRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 1;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendAppHeartbeatRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SendAppHeartbeatRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendAppHeartbeatRequest::GetClassData() const { return &_class_data_; }

void SendAppHeartbeatRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SendAppHeartbeatRequest *>(to)->MergeFrom(
      static_cast<const SendAppHeartbeatRequest &>(from));
}


void SendAppHeartbeatRequest::MergeFrom(const SendAppHeartbeatRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.SendAppHeartbeatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _internal_set_token(from._internal_token());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendAppHeartbeatRequest::CopyFrom(const SendAppHeartbeatRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.SendAppHeartbeatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendAppHeartbeatRequest::IsInitialized() const {
  return true;
}

void SendAppHeartbeatRequest::InternalSwap(SendAppHeartbeatRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &token_, lhs_arena,
      &other->token_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SendAppHeartbeatRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_getter, &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once,
      file_level_metadata_flwr_2fproto_2fheartbeat_2eproto[2]);
}

// ===================================================================

class SendAppHeartbeatResponse::_Internal {
 public:
};

SendAppHeartbeatResponse::SendAppHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:flwr.proto.SendAppHeartbeatResponse)
}
SendAppHeartbeatResponse::SendAppHeartbeatResponse(const SendAppHeartbeatResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.SendAppHeartbeatResponse)
}

void SendAppHeartbeatResponse::SharedCtor() {
success_ = false;
}

SendAppHeartbeatResponse::~SendAppHeartbeatResponse() {
  // @@protoc_insertion_point(destructor:flwr.proto.SendAppHeartbeatResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SendAppHeartbeatResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SendAppHeartbeatResponse::ArenaDtor(void* object) {
  SendAppHeartbeatResponse* _this = reinterpret_cast< SendAppHeartbeatResponse* >(object);
  (void)_this;
}
void SendAppHeartbeatResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendAppHeartbeatResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SendAppHeartbeatResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.SendAppHeartbeatResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendAppHeartbeatResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendAppHeartbeatResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.SendAppHeartbeatResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.SendAppHeartbeatResponse)
  return target;
}

size_t SendAppHeartbeatResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.SendAppHeartbeatResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendAppHeartbeatResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SendAppHeartbeatResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendAppHeartbeatResponse::GetClassData() const { return &_class_data_; }

void SendAppHeartbeatResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SendAppHeartbeatResponse *>(to)->MergeFrom(
      static_cast<const SendAppHeartbeatResponse &>(from));
}


void SendAppHeartbeatResponse::MergeFrom(const SendAppHeartbeatResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.SendAppHeartbeatResponse)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _internal_set_success(from._internal_success());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendAppHeartbeatResponse::CopyFrom(const SendAppHeartbeatResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.SendAppHeartbeatResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendAppHeartbeatResponse::IsInitialized() const {
  return true;
}

void SendAppHeartbeatResponse::InternalSwap(SendAppHeartbeatResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(success_, other->success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendAppHeartbeatResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_getter, &descriptor_table_flwr_2fproto_2fheartbeat_2eproto_once,
      file_level_metadata_flwr_2fproto_2fheartbeat_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::flwr::proto::SendNodeHeartbeatRequest* Arena::CreateMaybeMessage< ::flwr::proto::SendNodeHeartbeatRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::SendNodeHeartbeatRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::SendNodeHeartbeatResponse* Arena::CreateMaybeMessage< ::flwr::proto::SendNodeHeartbeatResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::SendNodeHeartbeatResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::SendAppHeartbeatRequest* Arena::CreateMaybeMessage< ::flwr::proto::SendAppHeartbeatRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::SendAppHeartbeatRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::SendAppHeartbeatResponse* Arena::CreateMaybeMessage< ::flwr::proto::SendAppHeartbeatResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::SendAppHeartbeatResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
