context: pytorch-deploy-dynamic
address: 0.0.0.0
port: 9100
tcp: true
udp: false

topology:
  mode: dynamic

sampling:
  algorithm: gbps
  config_file: ./config_sampling.json
  params:
    view_size: 4
    heal: 0
    swap: 0
    selection_policy: old
    propagation_policy: pushpull
    delay: 2
    age: 1
