"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import abc
import collections.abc
import flwr.proto.appio_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class AppIoStub:
    """These messages are used by both ServerAppIo and ClientAppIo services"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    CreateTask: grpc.UnaryUnaryMultiCallable[
        flwr.proto.appio_pb2.CreateTaskRequest,
        flwr.proto.appio_pb2.CreateTaskResponse,
    ]
    """Create a task"""

class AppIoAsyncStub:
    """These messages are used by both ServerAppIo and ClientAppIo services"""

    CreateTask: grpc.aio.UnaryUnaryMultiCallable[
        flwr.proto.appio_pb2.CreateTaskRequest,
        flwr.proto.appio_pb2.CreateTaskResponse,
    ]
    """Create a task"""

class AppIoServicer(metaclass=abc.ABCMeta):
    """These messages are used by both ServerAppIo and ClientAppIo services"""

    @abc.abstractmethod
    def CreateTask(
        self,
        request: flwr.proto.appio_pb2.CreateTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[flwr.proto.appio_pb2.CreateTaskResponse, collections.abc.Awaitable[flwr.proto.appio_pb2.CreateTaskResponse]]:
        """Create a task"""

def add_AppIoServicer_to_server(servicer: AppIoServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
