"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Conversation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONVERSATION_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    conversation_id: builtins.str
    run_id: builtins.int
    title: builtins.str
    created_at: builtins.float
    updated_at: builtins.float
    def __init__(
        self,
        *,
        conversation_id: builtins.str = ...,
        run_id: builtins.int = ...,
        title: builtins.str = ...,
        created_at: builtins.float = ...,
        updated_at: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["conversation_id", b"conversation_id", "created_at", b"created_at", "run_id", b"run_id", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

global___Conversation = Conversation

@typing.final
class ConversationItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONVERSATION_ID_FIELD_NUMBER: builtins.int
    ITEM_INDEX_FIELD_NUMBER: builtins.int
    ITEM_JSON_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    conversation_id: builtins.str
    item_index: builtins.int
    item_json: builtins.str
    created_at: builtins.float
    run_id: builtins.int
    task_id: builtins.int
    def __init__(
        self,
        *,
        conversation_id: builtins.str = ...,
        item_index: builtins.int = ...,
        item_json: builtins.str = ...,
        created_at: builtins.float = ...,
        run_id: builtins.int = ...,
        task_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_task_id", b"_task_id", "task_id", b"task_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_task_id", b"_task_id", "conversation_id", b"conversation_id", "created_at", b"created_at", "item_index", b"item_index", "item_json", b"item_json", "run_id", b"run_id", "task_id", b"task_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_task_id", b"_task_id"]) -> typing.Literal["task_id"] | None: ...

global___ConversationItem = ConversationItem

@typing.final
class ConversationItemPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_JSON_FIELD_NUMBER: builtins.int
    item_json: builtins.str
    def __init__(
        self,
        *,
        item_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["item_json", b"item_json"]) -> None: ...

global___ConversationItemPayload = ConversationItemPayload
