# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flwr/proto/conversation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'flwr/proto/conversation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66lwr/proto/conversation.proto\x12\nflwr.proto\"n\n\x0c\x43onversation\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\x04\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x01\x12\x12\n\nupdated_at\x18\x05 \x01(\x01\"\x98\x01\n\x10\x43onversationItem\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x12\n\nitem_index\x18\x02 \x01(\x04\x12\x11\n\titem_json\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x01\x12\x0e\n\x06run_id\x18\x05 \x01(\x04\x12\x14\n\x07task_id\x18\x06 \x01(\x04H\x00\x88\x01\x01\x42\n\n\x08_task_id\",\n\x17\x43onversationItemPayload\x12\x11\n\titem_json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flwr.proto.conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSATION']._serialized_start=45
  _globals['_CONVERSATION']._serialized_end=155
  _globals['_CONVERSATIONITEM']._serialized_start=158
  _globals['_CONVERSATIONITEM']._serialized_end=310
  _globals['_CONVERSATIONITEMPAYLOAD']._serialized_start=312
  _globals['_CONVERSATIONITEMPAYLOAD']._serialized_end=356
# @@protoc_insertion_point(module_scope)
