"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RunCollection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTION_ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    METADATA_JSON_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    LAST_RUN_ID_FIELD_NUMBER: builtins.int
    collection_id: builtins.str
    title: builtins.str
    metadata_json: builtins.str
    created_at: builtins.str
    updated_at: builtins.str
    last_run_id: builtins.int
    def __init__(
        self,
        *,
        collection_id: builtins.str = ...,
        title: builtins.str | None = ...,
        metadata_json: builtins.str = ...,
        created_at: builtins.str = ...,
        updated_at: builtins.str = ...,
        last_run_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_last_run_id", b"_last_run_id", "_title", b"_title", "last_run_id", b"last_run_id", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_last_run_id", b"_last_run_id", "_title", b"_title", "collection_id", b"collection_id", "created_at", b"created_at", "last_run_id", b"last_run_id", "metadata_json", b"metadata_json", "title", b"title", "updated_at", b"updated_at"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_run_id", b"_last_run_id"]) -> typing.Literal["last_run_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

global___RunCollection = RunCollection

@typing.final
class RunCollectionItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTION_ID_FIELD_NUMBER: builtins.int
    ITEM_INDEX_FIELD_NUMBER: builtins.int
    ITEM_JSON_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    ITEM_REF_FIELD_NUMBER: builtins.int
    PARENT_ITEM_REF_FIELD_NUMBER: builtins.int
    collection_id: builtins.str
    item_index: builtins.int
    item_json: builtins.str
    created_at: builtins.str
    run_id: builtins.int
    task_id: builtins.int
    item_ref: builtins.str
    parent_item_ref: builtins.str
    def __init__(
        self,
        *,
        collection_id: builtins.str = ...,
        item_index: builtins.int = ...,
        item_json: builtins.str = ...,
        created_at: builtins.str = ...,
        run_id: builtins.int | None = ...,
        task_id: builtins.int | None = ...,
        item_ref: builtins.str | None = ...,
        parent_item_ref: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_item_ref", b"_item_ref", "_parent_item_ref", b"_parent_item_ref", "_run_id", b"_run_id", "_task_id", b"_task_id", "item_ref", b"item_ref", "parent_item_ref", b"parent_item_ref", "run_id", b"run_id", "task_id", b"task_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_item_ref", b"_item_ref", "_parent_item_ref", b"_parent_item_ref", "_run_id", b"_run_id", "_task_id", b"_task_id", "collection_id", b"collection_id", "created_at", b"created_at", "item_index", b"item_index", "item_json", b"item_json", "item_ref", b"item_ref", "parent_item_ref", b"parent_item_ref", "run_id", b"run_id", "task_id", b"task_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_item_ref", b"_item_ref"]) -> typing.Literal["item_ref"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_parent_item_ref", b"_parent_item_ref"]) -> typing.Literal["parent_item_ref"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_run_id", b"_run_id"]) -> typing.Literal["run_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_task_id", b"_task_id"]) -> typing.Literal["task_id"] | None: ...

global___RunCollectionItem = RunCollectionItem

@typing.final
class RunCollectionItemPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_JSON_FIELD_NUMBER: builtins.int
    ITEM_REF_FIELD_NUMBER: builtins.int
    PARENT_ITEM_REF_FIELD_NUMBER: builtins.int
    item_json: builtins.str
    item_ref: builtins.str
    parent_item_ref: builtins.str
    def __init__(
        self,
        *,
        item_json: builtins.str = ...,
        item_ref: builtins.str | None = ...,
        parent_item_ref: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_item_ref", b"_item_ref", "_parent_item_ref", b"_parent_item_ref", "item_ref", b"item_ref", "parent_item_ref", b"parent_item_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_item_ref", b"_item_ref", "_parent_item_ref", b"_parent_item_ref", "item_json", b"item_json", "item_ref", b"item_ref", "parent_item_ref", b"parent_item_ref"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_item_ref", b"_item_ref"]) -> typing.Literal["item_ref"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_parent_item_ref", b"_parent_item_ref"]) -> typing.Literal["parent_item_ref"] | None: ...

global___RunCollectionItemPayload = RunCollectionItemPayload
