# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flwr/proto/runcollection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'flwr/proto/runcollection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66lwr/proto/runcollection.proto\x12\nflwr.proto\"\xad\x01\n\rRunCollection\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\x12\x18\n\x0blast_run_id\x18\x06 \x01(\x04H\x01\x88\x01\x01\x42\x08\n\x06_titleB\x0e\n\x0c_last_run_id\"\xfd\x01\n\x11RunCollectionItem\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\nitem_index\x18\x02 \x01(\x04\x12\x11\n\titem_json\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x13\n\x06run_id\x18\x05 \x01(\x04H\x00\x88\x01\x01\x12\x14\n\x07task_id\x18\x06 \x01(\x04H\x01\x88\x01\x01\x12\x15\n\x08item_ref\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0fparent_item_ref\x18\x08 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_run_idB\n\n\x08_task_idB\x0b\n\t_item_refB\x12\n\x10_parent_item_ref\"\x83\x01\n\x18RunCollectionItemPayload\x12\x11\n\titem_json\x18\x01 \x01(\t\x12\x15\n\x08item_ref\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fparent_item_ref\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_item_refB\x12\n\x10_parent_item_refb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flwr.proto.runcollection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNCOLLECTION']._serialized_start=47
  _globals['_RUNCOLLECTION']._serialized_end=220
  _globals['_RUNCOLLECTIONITEM']._serialized_start=223
  _globals['_RUNCOLLECTIONITEM']._serialized_end=476
  _globals['_RUNCOLLECTIONITEMPAYLOAD']._serialized_start=479
  _globals['_RUNCOLLECTIONITEMPAYLOAD']._serialized_end=610
# @@protoc_insertion_point(module_scope)
