# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add run collections.

Revision ID: f934b49300f8
Revises: 26b5d6018750
Create Date: 2026-05-26 16:04:15.523022
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "f934b49300f8"
down_revision: str | Sequence[str] | None = "26b5d6018750"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_collection",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("collection_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("last_run_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flwr_aid", "collection_id", name="uq_run_collection_flwr_aid_collection_id"
        ),
    )
    with op.batch_alter_table("run_collection", schema=None) as batch_op:
        batch_op.create_index(
            "idx_run_collection_flwr_aid_created_at",
            ["flwr_aid", "created_at"],
            unique=False,
        )

    op.create_table(
        "run_collection_item",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("collection_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("item_index", sa.BigInteger(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.Column("item_ref", sa.String(), nullable=True),
        sa.Column("parent_item_ref", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flwr_aid",
            "collection_id",
            "item_index",
            name="uq_run_collection_item_flwr_aid_collection_id_item_index",
        ),
    )
    with op.batch_alter_table("run_collection_item", schema=None) as batch_op:
        batch_op.create_index(
            "idx_run_collection_item_flwr_aid_collection_id_item_index",
            ["flwr_aid", "collection_id", "item_index"],
            unique=False,
        )
        batch_op.create_index(
            "idx_run_collection_item_flwr_aid_item_ref",
            ["flwr_aid", "item_ref"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_collection_item", schema=None) as batch_op:
        batch_op.drop_index("idx_run_collection_item_flwr_aid_item_ref")
        batch_op.drop_index("idx_run_collection_item_flwr_aid_collection_id_item_index")

    op.drop_table("run_collection_item")
    with op.batch_alter_table("run_collection", schema=None) as batch_op:
        batch_op.drop_index("idx_run_collection_flwr_aid_created_at")

    op.drop_table("run_collection")
    # ### end Alembic commands ###
