# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add app type to run series.

Revision ID: 42bb34a4bf38
Revises: a6f4d2c91b7e
Create Date: 2026-08-19 10:19:31.697913
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "42bb34a4bf38"
down_revision: str | Sequence[str] | None = "a6f4d2c91b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AGENT_APP_TYPE = "flwr-agentapp"
SERVER_APP_TYPE = "flwr-serverapp"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_series", schema=None) as batch_op:
        batch_op.add_column(sa.Column("app_type", sa.String(), nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE run_series
            SET app_type = COALESCE((
                SELECT CASE
                    WHEN task.type = :agent_app_type THEN :agent_app_type
                    ELSE :server_app_type
                END
                FROM series_runs
                JOIN run ON run.run_id = series_runs.run_id
                JOIN task ON task.task_id = run.primary_task_id
                WHERE series_runs.series_id = run_series.series_id
                ORDER BY series_runs.id
                LIMIT 1
            ), :server_app_type)
            """
        ).bindparams(
            agent_app_type=AGENT_APP_TYPE,
            server_app_type=SERVER_APP_TYPE,
        )
    )

    with op.batch_alter_table("run_series", schema=None) as batch_op:
        batch_op.alter_column(
            "app_type",
            existing_type=sa.String(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_series", schema=None) as batch_op:
        batch_op.drop_column("app_type")

    # ### end Alembic commands ###
