# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add federation agent table.

Revision ID: ac5badc54b38
Revises: 7208a0cbdcd7
Create Date: 2026-08-14 08:55:56.865567
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "ac5badc54b38"
down_revision: str | Sequence[str] | None = "7208a0cbdcd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federation_agent",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(), nullable=False),
        sa.Column("fab_hash", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "federation_id",
            "app_id",
            name="uq_federation_agent_federation_id_app_id",
        ),
    )
    with op.batch_alter_table("federation_agent", schema=None) as batch_op:
        batch_op.create_index(
            "idx_federation_agent_federation_id_created_at",
            ["federation_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_agent", schema=None) as batch_op:
        batch_op.drop_index("idx_federation_agent_federation_id_created_at")

    op.drop_table("federation_agent")
    # ### end Alembic commands ###
