# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add OAuth connector tables.

Revision ID: e2dd7937d7fc
Revises: 1289dca56546
Create Date: 2026-07-09 20:12:34.148401
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "e2dd7937d7fc"
down_revision: str | Sequence[str] | None = "1289dca56546"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("credentials_json", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flwr_aid", "connector_ref", name="uq_connector_flwr_aid_connector_ref"
        ),
    )

    op.create_table(
        "connector_oauth_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oauth_session_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("pkce_verifier", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oauth_session_id"),
    )
    with op.batch_alter_table("connector_oauth_session", schema=None) as batch_op:
        batch_op.create_index(
            "idx_connector_oauth_session_flwr_aid_status_expires_at",
            ["flwr_aid", "status", "expires_at"],
            unique=False,
        )

    op.create_table(
        "run_connector",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["flwr_aid", "connector_ref"],
            ["connector.flwr_aid", "connector.connector_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "flwr_aid",
            "connector_ref",
            name="uq_run_connector_run_id_flwr_aid_connector_ref",
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_connector")
    with op.batch_alter_table("connector_oauth_session", schema=None) as batch_op:
        batch_op.drop_index("idx_connector_oauth_session_flwr_aid_status_expires_at")

    op.drop_table("connector_oauth_session")
    op.drop_table("connector")
    # ### end Alembic commands ###
