# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Support multiple connector accounts.

Revision ID: cf1525eb62a7
Revises: f670d1ed8681
Create Date: 2026-09-23 16:49:48.736978
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from flwr.supercore.state.schema.types import UTCDateTime


# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "cf1525eb62a7"
down_revision: str | Sequence[str] | None = "f670d1ed8681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing connector sessions and bindings cannot be mapped unambiguously to
    # connection IDs, so connector data is intentionally reset by this migration.
    op.drop_table("run_connector")
    op.drop_table("connector_oauth_session")
    op.drop_table("connector")
    op.create_table(
        "connector",
        sa.Column("connector_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("credentials_json", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("deleted_at", UTCDateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("connector_id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "connector_oauth_session",
        sa.Column("oauth_session_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("pkce_verifier", sa.String(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=False),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("oauth_session_id"),
    )
    op.create_table(
        "run_connector",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("connector_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "connector_id"),
    )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("connector_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_connector")
    op.drop_table("connector_oauth_session")
    op.drop_table("connector")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("connector_id")
    op.create_table(
        "connector",
        sa.Column("connector_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("credentials_json", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("deleted_at", UTCDateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("connector_id"),
        sa.UniqueConstraint("federation_id", "connector_ref"),
    )
    op.create_table(
        "connector_oauth_session",
        sa.Column("oauth_session_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("pkce_verifier", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("oauth_session_id"),
    )
    op.create_table(
        "run_connector",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "connector_ref"),
    )

    # ### end Alembic commands ###
