# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Make primary_task_id not nullable.

Revision ID: dba626f15705
Revises: e566a1e755c5
Create Date: 2026-05-11 10:56:46.189647
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "dba626f15705"
down_revision: str | Sequence[str] | None = "e566a1e755c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill runs that already have tasks by reusing the earliest task as primary.
    op.execute(
        """
        UPDATE run
        SET primary_task_id = (
            SELECT task.task_id
            FROM task
            WHERE task.run_id = run.run_id
            ORDER BY task.pending_at ASC, task.task_id ASC
            LIMIT 1
        )
        WHERE primary_task_id IS NULL
        """
    )

    # Repair partial legacy writes by creating a primary task for runs that still
    # have no task row at all.
    op.execute(
        """
        WITH missing_runs AS (
            SELECT
                run_id,
                fab_hash,
                pending_at,
                CASE
                    WHEN run_type = 'simulation' THEN 'flwr-simulation'
                    WHEN run_type = 'serverapp' THEN 'flwr-serverapp'
                END AS task_type,
                ROW_NUMBER() OVER (ORDER BY run_id) AS row_num
            FROM run
            WHERE primary_task_id IS NULL
        ),
        new_tasks AS (
            SELECT
                (
                    SELECT COALESCE(MIN(task_id), 0)
                    FROM task
                ) - row_num AS task_id,
                task_type,
                run_id,
                fab_hash,
                pending_at
            FROM missing_runs
            WHERE task_type IS NOT NULL
        )
        INSERT INTO task (
            task_id,
            type,
            run_id,
            fab_hash,
            model_ref,
            connector_ref,
            token,
            active_until,
            pending_at,
            starting_at,
            running_at,
            finished_at,
            sub_status,
            details
        )
        SELECT
            task_id,
            task_type,
            run_id,
            fab_hash,
            NULL,
            NULL,
            NULL,
            NULL,
            pending_at,
            NULL,
            NULL,
            NULL,
            '',
            ''
        FROM new_tasks
        """
    )

    op.execute(
        """
        UPDATE run
        SET primary_task_id = (
            SELECT task.task_id
            FROM task
            WHERE task.run_id = run.run_id
            ORDER BY task.pending_at ASC, task.task_id ASC
            LIMIT 1
        )
        WHERE primary_task_id IS NULL
        """
    )

    remaining_null_count = op.get_bind().execute(
        sa.text(
            "SELECT COUNT(*) FROM run WHERE primary_task_id IS NULL"
        )
    ).scalar_one()
    if remaining_null_count:
        raise RuntimeError(
            "Cannot enforce NOT NULL on run.primary_task_id while NULL rows remain."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "primary_task_id",
            existing_type=sa.BIGINT(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "primary_task_id",
            existing_type=sa.BIGINT(),
            nullable=True,
        )

    # ### end Alembic commands ###
