# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add message delivery leases.

Revision ID: afcd7e71f1e4
Revises: 26b5d6018750
Create Date: 2026-05-26 15:53:05.990251
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "afcd7e71f1e4"
down_revision: str | Sequence[str] | None = "26b5d6018750"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message_ins", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lease_expires_at", sa.Float(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "acknowledged_at",
                sa.String(),
                server_default=sa.text("''"),
                nullable=False,
            )
        )

    with op.batch_alter_table("message_res", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lease_expires_at", sa.Float(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message_res", schema=None) as batch_op:
        batch_op.drop_column("lease_expires_at")

    with op.batch_alter_table("message_ins", schema=None) as batch_op:
        batch_op.drop_column("acknowledged_at")
        batch_op.drop_column("lease_expires_at")

    # ### end Alembic commands ###
