# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Index run FAB hash and federation ID.

Revision ID: 8f66eae2cbd9
Revises: 28482626dbdc
Create Date: 2026-08-03 16:42:47.580126
"""
from collections.abc import Sequence

from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "8f66eae2cbd9"
down_revision: str | Sequence[str] | None = "28482626dbdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(
            "idx_run_fab_hash_federation_id",
            ["fab_hash", "federation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index("idx_run_fab_hash_federation_id")

    # ### end Alembic commands ###
