# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add conversations.

Revision ID: f847f6e12e46
Revises: a6edd6ef01bd
Create Date: 2026-05-18 18:36:45.240586
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "f847f6e12e46"
down_revision: str | Sequence[str] | None = "a6edd6ef01bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.UniqueConstraint("conversation_id"),
    )
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.create_index(
            "idx_conversation_flwr_aid_updated_at",
            ["flwr_aid", "updated_at"],
            unique=False,
        )

    op.create_table(
        "conversation_item",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("item_index", sa.BigInteger(), nullable=False),
        sa.Column("item_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.conversation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.UniqueConstraint("conversation_id", "item_index"),
    )
    with op.batch_alter_table("conversation_item", schema=None) as batch_op:
        batch_op.create_index(
            "idx_conversation_item_conversation_id_item_index",
            ["conversation_id", "item_index"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_item", schema=None) as batch_op:
        batch_op.drop_index("idx_conversation_item_conversation_id_item_index")

    op.drop_table("conversation_item")
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.drop_index("idx_conversation_flwr_aid_updated_at")

    op.drop_table("conversation")
    # ### end Alembic commands ###
