# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Make run substatus and details not nullable.

Revision ID: 0d7337ff4c97
Revises: 8253e456d570
Create Date: 2026-04-28 14:04:41.639126
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "0d7337ff4c97"
down_revision: str | Sequence[str] | None = "8253e456d570"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE run SET sub_status = '' WHERE sub_status IS NULL")
    op.execute("UPDATE run SET details = '' WHERE details IS NULL")

    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "sub_status",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("('')"),
            nullable=False,
        )
        batch_op.alter_column(
            "details",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("('')"),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "details", existing_type=sa.VARCHAR(), server_default=None, nullable=True
        )
        batch_op.alter_column(
            "sub_status", existing_type=sa.VARCHAR(), server_default=None, nullable=True
        )

    # ### end Alembic commands ###
