# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Allow unpinned federation apps.

Revision ID: 0d434553973d
Revises: a6f4d2c91b7e
Create Date: 2026-08-18 17:16:45.282331
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "0d434553973d"
down_revision: str | Sequence[str] | None = "a6f4d2c91b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM federation_app WHERE fab_hash IS NULL"))
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
