# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add series run table.

Revision ID: 3974044eab04
Revises: f934b49300f8
Create Date: 2026-05-29 17:01:44.398816
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "3974044eab04"
down_revision: str | Sequence[str] | None = "f934b49300f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series_run",
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO series_run (series_id, run_id)
            SELECT series_id, run_id
            FROM run
            WHERE series_id IS NOT NULL AND run_id IS NOT NULL
            """
        )
    )
    with op.batch_alter_table("series_run", schema=None) as batch_op:
        batch_op.create_index("idx_series_run_series_id", ["series_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series_run", schema=None) as batch_op:
        batch_op.drop_index("idx_series_run_series_id")

    op.drop_table("series_run")
    # ### end Alembic commands ###
